<?php

/**
 * Test class for Com.
 * Generated by PHPUnit on 2010-12-14 at 21:52:29.
 */
class ComTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Com
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Com;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
